In [1]:
# numpy 라이브러리

In [2]:
import numpy as np

In [3]:
# array 생성하기
list1 = [1,2,3,4,5]
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
# 연산을 진행하면 각 요소끼리 연산을 진행
arr + arr1

array([ 2,  4,  6,  8, 10])

In [6]:
arr * arr1

array([ 1,  4,  9, 16, 25])

In [7]:
# 리스트
# [1,2,3], [4,5,6] 각 요소의 값을 더한다

In [8]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = []
for i in range(3):
    list3.append(list1[i]+list2[i])
list3

[5, 7, 9]

In [9]:
# 2차원 array 생성하기
arr2 = np.array( [[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# array의 크기 확인하기
# shape
arr2.shape

(2, 3)

In [11]:
# array의 전체 요소 개수 확인하기
# size
arr2.size

6

In [12]:
# array의 타입 확인하기
# dtype
arr2.dtype

dtype('int32')

In [13]:
# array의 차원 확인하기
# ndim
arr2.ndim

2

In [14]:
# 3차원의 array만들고 배열의 크기, 차원, 전체 요소개수 확인
arr3 = np.array([ [[1,2],[3,4]],[[5,6],[7,8]] ])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
print(f'배열의 크기 : {arr3.shape}')
print(f'배열의 차원 : {arr3.ndim}')
print(f'배열의 개수 : {arr3.size}')

배열의 크기 : (2, 2, 2)
배열의 차원 : 3
배열의 개수 : 8


In [16]:
# 배열 생성하기
# 0값으로 생성하기
# zeros (배열의 크기)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# 1값으로 생성하기
# ones()
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# 지정해서 생성하기
# full (배열의 크기, 채워넣을 값)
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [19]:
# 연속되는 숫자로 배열 생성하기
# arange (시작하는 수, 끝나는 수 +1, 간격이되는 수)
# 시작하는 수 기본값 : 0
# 간격이 되는 수 기본값 : 1
np.arange(0,50,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
# [1,11,21,31,41] 이 들어가있는 array 만들기
np.arange(1,42,10)

array([ 1, 11, 21, 31, 41])

In [21]:
# 1부터 50까지 1씩 커지는 배열 만들기
# np.linspace(시작하는 수, 끝나는 수, 등분할 값)
# 같은 간격만큼의 배열을 만들 때 사용
np.linspace(1,50,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [23]:
for i in np.linspace(1,50,20):
    print(i)

1.0
3.5789473684210527
6.157894736842105
8.736842105263158
11.31578947368421
13.894736842105264
16.473684210526315
19.05263157894737
21.63157894736842
24.210526315789473
26.789473684210527
29.36842105263158
31.94736842105263
34.526315789473685
37.10526315789474
39.68421052631579
42.26315789473684
44.8421052631579
47.421052631578945
50.0


In [24]:
# 랜덤값으로 배열 생성하기
# np.random.rand(배열의 크기)
# 0 ~ 1 사이의 값을 가지는 배열을 생성
np.random.rand(2,3)

array([[0.71744149, 0.99640623, 0.8914887 ],
       [0.25829532, 0.88261228, 0.82494592]])

In [27]:
# 원하는 범위에서 랜덤값 생성
# np.random.randint(시작수, 끝수+1, size = 배열의 크기)
np.random.randint(2,10, size = (3,2))

array([[6, 8],
       [8, 2],
       [4, 5]])

In [ ]:
# 2부터 10까지의 랜덤한 실수값으로 이루어진 (5,4) 크기의 배열 생성
# np.random.rand, np.random.randint 사용

In [44]:
# 정수 + 소숫점 = 실수
정수 = np.random.randint(2,10, size = (5,4))
정수

array([[2, 5, 6, 6],
       [6, 3, 8, 7],
       [7, 2, 5, 6],
       [3, 4, 6, 9],
       [2, 3, 2, 7]])

In [45]:
소숫점 = np.random.rand(5,4)
소숫점

array([[0.45358344, 0.04169654, 0.03285211, 0.64514858],
       [0.66645131, 0.1263393 , 0.10548678, 0.68314202],
       [0.75732142, 0.86909598, 0.278153  , 0.17759955],
       [0.26006846, 0.56460982, 0.62225921, 0.95085006],
       [0.47729082, 0.11458636, 0.48766518, 0.36033532]])

In [47]:
num = 정수 + 소숫점
num

array([[2.45358344, 5.04169654, 6.03285211, 6.64514858],
       [6.66645131, 3.1263393 , 8.10548678, 7.68314202],
       [7.75732142, 2.86909598, 5.278153  , 6.17759955],
       [3.26006846, 4.56460982, 6.62225921, 9.95085006],
       [2.47729082, 3.11458636, 2.48766518, 7.36033532]])

In [48]:
# 타입 변경하기
# 배열, astype(변경 할 타입)

In [49]:
num.astype("int")

array([[2, 5, 6, 6],
       [6, 3, 8, 7],
       [7, 2, 5, 6],
       [3, 4, 6, 9],
       [2, 3, 2, 7]])